# Generated by Django 4.1.4 on 2022-12-24 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('check', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='fullname',
            field=models.CharField(default='fullname', max_length=150, verbose_name='ФИО'),
            preserve_default=False,
        ),
    ]
