# Generated by Django 4.1.4 on 2022-12-26 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('check', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='isStudent',
            field=models.BooleanField(default=True, verbose_name='Является студентом'),
        ),
    ]
