# Generated by Django 4.1.4 on 2022-12-24 18:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('check', '0003_alter_user_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('MATH', 'Математика'), ('PHYS', 'Физика'), ('ALG', 'Алгебра'), ('DRG', 'Рисование'), ('CHM', 'Химия'), ('HSTR', 'История'), ('MSC', 'Музыка'), ('BIO', 'Биология')], default='MATH', max_length=4, verbose_name='Предмет')),
                ('lesson_order', models.CharField(choices=[('LESSON1', 'Первый урок'), ('LESSON2', 'Второй урок'), ('LESSON3', 'Третий урок'), ('LESSON4', 'Червертый урок'), ('LESSON5', 'Пятый урок'), ('LESSON6', 'Шестой урок')], default='LESSON1', max_length=7, verbose_name='Порядковый номер урока')),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Mark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='check.lesson')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='lesson',
            name='lesson',
            field=models.ManyToManyField(through='check.Mark', to=settings.AUTH_USER_MODEL),
        ),
    ]
